// <auto-generated />
using System.Collections.Generic;
using AcervoFilmes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcervoFilmes.Migrations
{
    [DbContext(typeof(AcervoFilmeDbContext))]
    partial class AcervoFilmeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcervoFilmes.Models.AvaliacaoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FilmeTitulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilmeTitulo");

                    b.ToTable("avaliacoes");
                });

            modelBuilder.Entity("AcervoFilmes.Models.FilmeModel", b =>
                {
                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<int>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("integer");

                    b.Property<int>("Genero")
                        .HasColumnType("integer");

                    b.Property<int>("Mes")
                        .HasMaxLength(2)
                        .HasColumnType("integer");

                    b.Property<List<string>>("StreamingsDisponivel")
                        .HasMaxLength(255)
                        .HasColumnType("text[]");

                    b.HasKey("Titulo");

                    b.ToTable("filmes");
                });

            modelBuilder.Entity("AcervoFilmes.Models.AvaliacaoModel", b =>
                {
                    b.HasOne("AcervoFilmes.Models.FilmeModel", "Filme")
                        .WithMany()
                        .HasForeignKey("FilmeTitulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Filme");
                });
#pragma warning restore 612, 618
        }
    }
}
